import json
questions = [
    {"id": "1","question":"Where is Rochester located?"},
    {"id": "2", "question": "How many states does the United States have?"},
    {"id": "3", "question": "Who is the president of the US?"},
    {"id": "4", "question": "Give me a list of top 5 restaurants in New York."},
    {"id": "5", "question": "Who is the best soccer player of all time?"},
    {"id": "6", "question": "What is the capital of France?"},
    {"id": "7", "question": "How many continents are there in the world?"},
    {"id": "8", "question": "What is the tallest mountain on Earth?"},
    {"id": "9", "question": "Who wrote 'To Kill a Mockingbird'?"},
    {"id": "10", "question": "What is the largest ocean on Earth?"},
    {"id": "11", "question": "Who painted the Mona Lisa?"},
    {"id": "12", "question": "What is the longest river in the world?"},
    {"id": "13", "question": "How many planets are in our solar system?"},
    {"id": "14", "question": "What is the speed of light?"},
    {"id": "15", "question": "Who is the founder of Microsoft?"},
    {"id": "16", "question": "Which country won the last FIFA World Cup?"},
    {"id": "17", "question": "What is the most spoken language in the world?"},
    {"id": "18", "question": "Who was the first person to walk on the moon?"},
    {"id": "19", "question": "What is the smallest country in the world?"},
    {"id": "20", "question": "What is the currency of Japan?"},
    {"id": "21", "question": "Who discovered gravity?"},
    {"id": "22", "question": "What is the boiling point of water in Celsius?"},
    {"id": "23", "question": "Where is the Great Wall of China located?"},
    {"id": "24", "question": "What is the chemical symbol for gold?"},
    {"id": "25", "question": "Who invented the telephone?"},
    {"id": "26", "question": "What is the largest mammal in the world?"},
    {"id": "27", "question": "Who directed the movie 'Inception'?"},
    {"id": "28", "question": "What is the national dish of Italy?"},
    {"id": "29", "question": "Which planet is known as the Red Planet?"},
    {"id": "30", "question": "What is the most popular sport in the world?"},
    {"id": "31", "question": "Where is the Statue of Liberty located?"},
    {"id": "32", "question": "Who is known as the Father of Computers?"},
    {"id": "33", "question": "What is the hardest natural substance on Earth?"},
    {"id": "34", "question": "Who composed Beethoven's Symphony No. 5?"},
    {"id": "35", "question": "Which element has the atomic number 1?"},
    {"id": "36", "question": "What is the capital of Australia?"},
    {"id": "37", "question": "How many bones are in the human body?"},
    {"id": "38", "question": "Who wrote the play 'Romeo and Juliet'?"},
    {"id": "39", "question": "What is the largest desert in the world?"},
    {"id": "40", "question": "Who won the first Nobel Prize in Physics?"},
    {"id": "41", "question": "What is the deepest ocean trench on Earth?"},
    {"id": "42", "question": "Where is Machu Picchu located?"},
    {"id": "43", "question": "What is the value of Pi up to two decimal places?"},
    {"id": "44", "question": "Who was the first female Prime Minister of the UK?"},
    {"id": "45", "question": "What is the most downloaded app of all time?"},
    {"id": "46", "question": "Who invented the World Wide Web?"},
    {"id": "47", "question": "What is the hottest planet in our solar system?"},
    {"id": "48", "question": "What is the national flower of Japan?"},
    {"id": "49", "question": "Which country is known as the Land of the Rising Sun?"},
    {"id": "50", "question": "Who was the first president of the United States?"}
]


